### ISSUE TITLE
combine "Marauder" and "Human" planets

### ISSUE THREAD

**Issue by LocalGod79** [Wrzlprnft/world-forge#11]
four landing points in a system causes u.i. overlap in the ports map screen

**Comment by Wrzlprnft** [comment]
We can actually merge all of them into earth

**Comment by LocalGod79** [comment]
you could add them all, or you could leave it as it after merging #13 - there's no identification in the shipyard, so it's pretty confusing when you see 3 of each Marauder Ship in the 'yard...

**Comment by Wrzlprnft** [comment]
I agree, we still can change it if there is feedback towards it.
