### ISSUE TITLE
break up your uber-omni-file

### ISSUE THREAD

**Issue by LocalGod79** [Wrzlprnft/world-forge#14]
perhaps, for the moment;
map.txt
shipyards.txt
outfitters.txt (contains licenses)
jobs.txt

i assure you that having multiple files for something like this is easier in the long run (and will reduce conflicts as you gather more collaborators)

**Comment by Wrzlprnft** [comment]
It probably is. It just started out as a fairly small file.

**Comment by Wrzlprnft** [comment]
thx derpy
