### ISSUE TITLE
Map Reveal

### ISSUE THREAD

**Issue by Wrzlprnft** [Wrzlprnft/world-forge#23]
World forge needs something to reveal the map. ill try to work something out if i have time but i didn't finish the arena yet.

**Comment by Amazinite** [comment]
What do you mean by "reveal the map?" Show the entire map once you enter the Milky Way?

**Comment by Wrzlprnft** [comment]
Like the local Map. But not local.
Maybe by a map, or a mission. Maybe the complete map, maybe just the labeled parts.
The point is, that, if one starts a new pilot for testing, you always have to explore around,. would be easier with the map.

**Comment by Amazinite** [comment]
I have a galactic map in my mod that will reveal pretty much all of human space when you buy it, but that would need to be bought while in human space and doesn't show any of the alien systems. Maybe you could have a job that you are able to pick up that makes a stopover on all vanilla systems, meaning that you would practically be able to see all the systems but not their links. That would just require a lot of stopover lines.

**Comment by Wrzlprnft** [comment]
I've found a copied list of all systems visited on reddit i think. Maybe i can use that.

**Comment by Wrzlprnft** [comment]
update: will use something like derpys galactic map, but within a mission shell: the player can buy a dummy or activate a mission, which adds in links, to link everything to the forge, gives the player the map, and then removes the links again.

**Comment by Amazinite** [comment]
```
event "pug flee"
    unvisit Deneb
    system "Zeta Aquilae"
        fleet "Small Southern Merchants" 1000
        ...
```

Notice the unvisit line. Maybe you can do the same thing with visit.

**Comment by Wrzlprnft** [comment]
That hijacks quite a bit my plan for the lazy version with the links but allows a idiot proof one (i hope)

**Comment by Amazinite** [comment]
027b777
