### ISSUE TITLE
advertisement

### ISSUE THREAD

**Issue by Wrzlprnft** [Wrzlprnft/world-forge#29]
I think this is great so far, after the arena is finished and the map thing is added, i am gonna make a release tag, and that one should get advertised. Ill seperate it into it's own thread on steam, and maybe we can pin it as some sort of "tool"?

Because some problems i see on github can be solved with this thing, and if it's just for easier test circumstances.

Any further ideas?

**Comment by Amazinite** [comment]
I think that sounds good. I will probably create a "Modding Tools" thread that links to important things like this or some of Legolas' stuff.

**Comment by Wrzlprnft** [comment]
good idea.

I asked takarada to post a reddit topic once we made a release here.
