### ISSUE TITLE
Player swizzle change

### ISSUE THREAD

**Issue by Wrzlprnft** [Wrzlprnft/world-forge#30]
I might want to have a look at earl greys mod for that, though.

**Comment by Amazinite** [comment]
Saw the title and was going to suggest that.

**Comment by Wrzlprnft** [comment]
I'm halfway through it.
Earls method spams the players savefile with events if i read it right, so i am working on something slightly different.

**Comment by Wrzlprnft** [comment]
For the record: i just added a system working the same way as earls. i think i gave credit properly by mentioning it everywhere.
