### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by Amazinite** [Wrzlprnft/world-forge#33]
https://github.com/endless-sky/endless-sky/issues/1465

No matter the location, they can be purchased if there is an outfit of that licenses somewhere, even if only in the data files.

This means that you can buy ships normally set behind licenses if World Forge is installed.

Maybe set the credit cost to something super high so that the only realistic way to get them is to use the credits job.

**Comment by Wrzlprnft** [comment]
or we move it to missions.

**Comment by Amazinite** [comment]
That too; for the sake of not having Forge's jobs board be so cluttered, we should have a moon around it just for licenses.

**Comment by Wrzlprnft** [comment]
i like the idea, this also allows players which do want nothing but the licenses (coughNAVYcough) to just get the navy license and no spoilers.

**Comment by Amazinite** [comment]
#36
