### ISSUE TITLE
Bunks in Korath outfitter

### ISSUE THREAD

**Issue by ReimeiSky** [Wrzlprnft/world-forge#38]
There aren't.
There should be.
Because otherwise the Command Center is useless.

**Comment by Amazinite** [comment]
Suggest moving bunks from human to basics.

**Comment by ReimeiSky** [comment]
unrelated, but I found that the control transceiver was missing.
probably because it's hard to spell anything with "ceiver" at the end.

**Comment by Amazinite** [comment]
Lol, yeah.

**Comment by Amazinite** [comment]
#39
