### ISSUE TITLE
Remove start?

### ISSUE THREAD

**Issue by Amazinite** [Wrzlprnft/world-forge#43]
Or at least move it so that you start on the default planet and then have the start convo for World Forge be an addition to the normal convo (pretty much just to say that World Forge has successfully been installed, and give directions to Nocte for new players). Reason being to make it just all around easier if you want a fresh start that doesn't seem cheaty.

**Comment by Wrzlprnft** [comment]
I had the same idea: do not change the start at all. Do not even add the wormhole. But have the player asked after the initial start convo: do you want to activate world forge? Yes-no-remind me in 10(0) ingame years.

The mission would trigger an event which would spawn the wormhole. Less likely to be overriden by another mod.

**Comment by LocalGod79** [comment]
this is an interesting thought - i think the 10year marker should just tell them to go to Nocte...

**Comment by Amazinite** [comment]
I changed the start to be on New Boston in 58f4e1a, which is what this issue is about, so I'm going to close this. If we want to allow the user to delay the opening of the wormhole to a later date than we can discuss that later, but I don't really see a need for it aside from people who don't really have the self control to not go to Nocte, in which case they should probably just remove the plugin anyways. xD
